### ISSUE TITLE
How to use in front-end scenarios?

### ISSUE THREAD

**Issue by chenkaiC4** [offscriptio/hasura-supertokens#24]
hi, thanks for reply me at supertokens discord. i have read this repo, use a webhook to extend a api for inserting user by hasura admin secret and a api (a webhook means to hasura) to be called by hasura for auth api.

There is a problem with this approach. Every api request needs to call webhook. Hasura recommends using the jwt method, so that after the auth service issues a jwt token, the front end can directly request the hasura api, and there is no need to go through the middle webhook again.

**Comment by chenkaiC4** [comment]
now, supertokens will sign a session, and the jwt payload can be add to it. but what is still not clear to me is how to get a  jwt token like this [demo](https://jwt.io/#debugger-io?token=eyJ1aWQiOiJjNDM5YTZhNC0wOWNhLTQ5NjctYjc4My01NWY1ZWQwNjM3MTMiLCJhdGUiOjE2MjI0MjkxMTcxMzksImFsZyI6IkhTMjU2In0.eyJzdXBlcnRva2VucyI6eyJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJ0ZXN0IiwieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ0ZXN0IiwiYWRtaW4iXX19.h76uX-389su3jzT6raUeWcx30xw-evdJOPu0j6X8CPE)

**Comment by gusfune** [comment]
Hi @chenkaiC4 with the webhook setup you need to get from your front-end both the `user-id` and the `session-id` and pass those in a header request to hasura as: `x-hasura-user-id` and `x-hasura-session-id`. If you want to use multiple roles then you also need to pass `x-hasura-role` in the header. If the user has that role, then it will authenticate with that role, otherwise will fallback to `user` if doesn't have a role, or `anonymous` if the user/session don't match.
